# ---------------------------------------------------------------------------
# The safety net for the 1.3 refactor.
#
# tests/testthat/fixtures/reference-values.rds holds the Results-table output of
# v1.2.2 for 3,732 option combinations - every analysis crossed with every
# distribution mode and every quantile mode, over a grid of parameters. It was
# generated by tools/make-reference-fixture.R, which computes each value twice
# by independent routes (a line-for-line transcription of the old .b.R files,
# and direct summation / Monte Carlo from first principles) and refuses to write
# the file unless they agree.
#
# The arithmetic in v1.2.2 was correct. This file's job is to prove the refactor
# did not move any of it.
#
# IMPORTANT: the subject under test switches automatically. While
# R/distribution-core.R does not exist, these tests check the transcription
# (which is what the fixture was built from, so they are near-tautological and
# only prove the fixture round-trips). The moment that file appears, they check
# the real core instead - and error rather than fall back if it does not expose
# what they need. That switch is what makes this a real net.
# ---------------------------------------------------------------------------

# helper-core.R has already sourced R/distribution-core.R if it exists.
core_path <- testthat::test_path("..", "..", "R", "distribution-core.R")
core_present <- file.exists(core_path)

characterization_subject <- local({
    if (!core_present) return(reference_run)
    if (!core_loaded)
        stop("R/distribution-core.R exists but does not define distributionResults(); ",
             "the characterization tests refuse to silently fall back to the ",
             "transcription they were generated from.")
    get("distributionResults", envir = globalenv())
})

test_that("the fixture is present and intact", {
    fx <- readRDS(testthat::test_path("fixtures", "reference-values.rds"))
    expect_gt(nrow(fx), 3000)
    expect_setequal(unique(fx$dist),
                    c("normal", "t", "chi2", "f", "binomial", "poisson", "geom", "hyper"))
    # no probability may have escaped [0, 1]
    expect_true(all(is.na(fx$probability) |
                    (fx$probability >= -1e-12 & fx$probability <= 1 + 1e-12)))
})

# Rows the fixture recorded that v1.3 deliberately no longer computes.
#
# v1.2.2 clamped out-of-range hypergeometric parameters into range and answered
# the clamped question silently. v1.3 rejects them instead, so those rows have
# no v1.3 counterpart by design. Everything else must still match to the bit.
fixtureRejected <- function(fx) {
    if (!core_present) return(rep(FALSE, nrow(fx)))
    vapply(seq_len(nrow(fx)), function(i) {
        r <- fx[i, ]
        o <- list(dp1 = r$dp1, dp2 = r$dp2, dp3 = r$dp3, x1 = r$x1, x2 = r$x2,
                  p = r$p, showDist = !is.na(r$distMode), distMode = r$distMode,
                  showQuant = !is.na(r$quantMode), quantMode = r$quantMode)
        !is.null(distributionValidate(distSpec(r$dist), o))
    }, logical(1))
}

test_that("the only rows v1.3 stops computing are the ones it now rejects", {
    skip_if_not(core_present)
    fx <- readRDS(testthat::test_path("fixtures", "reference-values.rds"))
    rej <- fixtureRejected(fx)

    # Every rejected row is hypergeometric with K or n exceeding N - the case
    # v1.2.2 silently clamped. Nothing else may have been swept up.
    expect_true(all(fx$dist[rej] == "hyper"))
    expect_true(all(fx$dp2[rej] > fx$dp1[rej] | fx$dp3[rej] > fx$dp1[rej]))
    # and the converse: every such row is rejected
    bad <- fx$dist == "hyper" & (fx$dp2 > fx$dp1 | fx$dp3 > fx$dp1)
    expect_identical(rej, bad)
})

test_that(paste0("every recorded result reproduces exactly (subject: ",
                 if (core_present) "distribution-core" else "v1.2.2 transcription", ")"), {
    fx  <- readRDS(testthat::test_path("fixtures", "reference-values.rds"))
    rej <- fixtureRejected(fx)
    fx  <- fx[!rej, ]
    expect_gt(nrow(fx), 3000)   # the exclusions must stay a small minority

    mismatches <- list()
    for (i in seq_len(nrow(fx))) {
        row <- fx[i, ]
        o <- list(dp1 = row$dp1, dp2 = row$dp2, dp3 = row$dp3,
                  x1 = row$x1, x2 = row$x2, p = row$p)
        got <- characterization_subject(row$dist, o, row$distMode, row$quantMode)

        for (k in c("probability", "quantile", "quantileLower", "quantileUpper",
                    "mean", "sd")) {
            want <- row[[k]]; have <- got[[k]]
            ok <- (is.na(want) && is.na(have)) ||
                  (is.nan(want) && is.nan(have)) ||
                  (is.finite(want) && is.finite(have) &&
                   abs(want - have) <= 1e-12 * max(1, abs(want)))
            if (!isTRUE(ok))
                mismatches[[length(mismatches) + 1]] <- sprintf(
                    "%s/%s/%s %s: expected %s, got %s (dp1=%s dp2=%s dp3=%s x1=%s x2=%s p=%s)",
                    row$dist, row$distMode, row$quantMode, k,
                    format(want), format(have),
                    row$dp1, row$dp2, row$dp3, row$x1, row$x2, row$p)
        }
    }

    if (length(mismatches))
        fail(paste0(length(mismatches), " value(s) moved:\n",
                    paste(utils::head(mismatches, 20), collapse = "\n")))
    else
        succeed()
})
